title: Guopeng Li
position: Ph.D. Candidate
affiliation: Delft University of Technology (Netherlands)
email: G.Li-5@tudelft.nl
keywords: minimal academic
github_link: https://github.com/RomainLITUD
linkedin: https://www.linkedin.com/in/guopeng-li-120b02172/
avatar: ./assets/img/photo.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Update Oct. 2022.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
